services:
  server:
    build:
      context: ./SERVER
      dockerfile: Dockerfile
    container_name: spring-boot-server
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQL10Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - boss-network

  client:
    build:
      context: ./CLIENT
      dockerfile: Dockerfile
    container_name: typescript-client
    ports:
      - "5050:5000"
    environment:
      VITE_BACKEND_URL: http://localhost:8080
      BACKEND_HOST: server
      BACKEND_PORT: 8080
    depends_on:
      - server
    networks:
      - boss-network

networks:
  boss-network:
    driver: bridge
