services:
  server:
    build:
      context: ./SERVER
      dockerfile: Dockerfile
    container_name: spring-boot-server
    ports:
      - "6060:6000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQL10Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - boss-network
    env_file:
      - .env

  client:
    build:
      context: ./CLIENT
      dockerfile: Dockerfile
    container_name: typescript-client
    ports:
      - "5050:5000"
    environment:
      # 브라우저에서 접근할 때는 호스트 포트 사용
      - BACKEND_URL=http://localhost:6060
      # 컨테이너 내부 통신용 (서비스 이름 사용)
      - BACKEND_HOST=server
      - BACKEND_PORT=6000
    depends_on:
      - server
    networks:
      - boss-network

networks:
  boss-network:
    driver: bridge

